window.NEARCONNECT_SUPABASE_URL = 'https://vtezfkktbrtdnxeayjjm.supabase.co';
window.NEARCONNECT_SUPABASE_ANON_KEY = 'YOUR_SUPABASE_ANON_KEY';
window.NEARCONNECT_FUNCTIONS_BASE = 'https://YOUR_PROJECT.supabase.co/functions/v1';
window.NEARCONNECT_ADMIN_MASTER_KEY = 'CHANGE_ME_ONLY_FOR_ADMIN_TESTS';
